CREATE TABLE parking_space
(
    parking_space_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code             VARCHAR(255),
    occupied         BOOLEAN,
    department_id    BIGINT,
    CONSTRAINT pk_parkingspace PRIMARY KEY (parking_space_id)
);

CREATE TABLE department
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE motorcycle
(
    id_motorcycle    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plate            VARCHAR(255),
    model            VARCHAR(255),
    color            VARCHAR(255),
    parking_space_id BIGINT,
    CONSTRAINT pk_motorcycle PRIMARY KEY (id_motorcycle)
);

ALTER TABLE motorcycle
    ADD CONSTRAINT FK_MOTORCYCLE_ON_PARKING_SPACE FOREIGN KEY (parking_space_id) REFERENCES parking_space (parking_space_id);

ALTER TABLE parking_space
    ADD CONSTRAINT FK_PARKINGSPACE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE motorcycle
    ADD CONSTRAINT uc_motorcycle_parking_space UNIQUE (parking_space_id);

CREATE TABLE alert
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message         VARCHAR(255),
    level_alert     VARCHAR(255),
    date_time_alert TIMESTAMP WITHOUT TIME ZONE,
    department_id   BIGINT,
    CONSTRAINT pk_alert PRIMARY KEY (id)
);

CREATE TABLE movement
(
    id_movement                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                           VARCHAR(255),
    motorcycle_id_motorcycle       BIGINT,
    parking_space_parking_space_id BIGINT,
    date_time_movement             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_movement PRIMARY KEY (id_movement)
);

ALTER TABLE alert
    ADD CONSTRAINT FK_ALERT_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE movement
    ADD CONSTRAINT FK_MOVEMENT_ON_MOTORCYCLE_IDMOTORCYCLE FOREIGN KEY (motorcycle_id_motorcycle) REFERENCES motorcycle (id_motorcycle);

ALTER TABLE movement
    ADD CONSTRAINT FK_MOVEMENT_ON_PARKINGSPACE_PARKINGSPACEID FOREIGN KEY (parking_space_parking_space_id) REFERENCES parking_space (parking_space_id);

ALTER TABLE alert
    ADD COLUMN active BOOLEAN DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS dashuser (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    avatarurl VARCHAR(255)  -- MUDEI: avatar_url → avatarurl
    );

CREATE TABLE IF NOT EXISTS dashuser_roles (
                                              user_id BIGINT NOT NULL,
                                              roles VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, roles),
    FOREIGN KEY (user_id) REFERENCES dashuser(id)
    );

