CREATE TABLE parking_space
(
    parking_space_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code             VARCHAR(255),
    occupied         BOOLEAN,
    department_id    BIGINT,
    CONSTRAINT pk_parkingspace PRIMARY KEY (parking_space_id)
);

CREATE TABLE department
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE motorcycle
(
    id_motorcycle    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plate            VARCHAR(255),
    model            VARCHAR(255),
    color            VARCHAR(255),
    parking_space_id BIGINT,
    CONSTRAINT pk_motorcycle PRIMARY KEY (id_motorcycle)
);

ALTER TABLE motorcycle
    ADD CONSTRAINT FK_MOTORCYCLE_ON_PARKING_SPACE FOREIGN KEY (parking_space_id) REFERENCES parking_space (parking_space_id);

ALTER TABLE parking_space
    ADD CONSTRAINT FK_PARKINGSPACE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE motorcycle
    ADD CONSTRAINT uc_motorcycle_parking_space UNIQUE (parking_space_id);