CREATE TABLE alert
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message         VARCHAR(255),
    level_alert     VARCHAR(255),
    date_time_alert TIMESTAMP WITHOUT TIME ZONE,
    department_id   BIGINT,
    CONSTRAINT pk_alert PRIMARY KEY (id)
);

CREATE TABLE movement
(
    id_movement                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                           VARCHAR(255),
    motorcycle_id_motorcycle       BIGINT,
    parking_space_parking_space_id BIGINT,
    date_time_movement             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_movement PRIMARY KEY (id_movement)
);

ALTER TABLE alert
    ADD CONSTRAINT FK_ALERT_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE movement
    ADD CONSTRAINT FK_MOVEMENT_ON_MOTORCYCLE_IDMOTORCYCLE FOREIGN KEY (motorcycle_id_motorcycle) REFERENCES motorcycle (id_motorcycle);

ALTER TABLE movement
    ADD CONSTRAINT FK_MOVEMENT_ON_PARKINGSPACE_PARKINGSPACEID FOREIGN KEY (parking_space_parking_space_id) REFERENCES parking_space (parking_space_id);