CREATE TABLE IF NOT EXISTS dashuser (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    avatarurl VARCHAR(255)  -- MUDEI: avatar_url → avatarurl
    );

CREATE TABLE IF NOT EXISTS dashuser_roles (
                                              user_id BIGINT NOT NULL,
                                              roles VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, roles),
    FOREIGN KEY (user_id) REFERENCES dashuser(id)
    );

-- INSERÇÃO DO USUÁRIO ADMINISTRADOR FIXO
INSERT INTO dashuser (email, name, avatarurl)
VALUES ('felipe08santanasantos@gmail.com', 'Admin Inicial', 'https://lh3.googleusercontent.com/a/ACg8ocL0TyNocamnF1XrPYpB2f0K2f60yYsIuEPmZpL1AB_sHoX4AQ=s96-c')
    ON CONFLICT (email) DO NOTHING;

-- Atribui a permissão ROLE_ADMIN
INSERT INTO dashuser_roles (user_id, roles)
SELECT id, 'ROLE_ADMIN'
FROM dashuser
WHERE email = 'felipe08santanasantos@gmail.com'
    ON CONFLICT DO NOTHING;

-- Atribui a permissão ROLE_USER
INSERT INTO dashuser_roles (user_id, roles)
SELECT id, 'ROLE_USER'
FROM dashuser
WHERE email = 'felipe08santanasantos@gmail.com'
    ON CONFLICT DO NOTHING;